name: coverage
version: 0.7.7-dev
author: Dart Team <misc@dartlang.org>
description: Coverage data manipulation and formatting
homepage: https://github.com/dart-lang/coverage
environment:
  sdk: '>=1.16.0 <2.0.0'
dependencies:
  args: '>=0.12.1 <1.0.0'
  async: ^1.8.0
  logging: '>=0.9.0 <0.12.0'
  path: '>=0.9.0 <2.0.0'
  stack_trace: ^1.3.0
  vm_service_client: ^0.2.2+1
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
executables:
  collect_coverage:
  format_coverage:
