name: coverage
version: 0.5.0
author: Dart Team <misc@dartlang.org>
description: Coverage data manipulation and formatting
homepage: https://github.com/dart-lang/coverage
environment:
  sdk: '>=1.4.0 <2.0.0'
dependencies:
  args: '>=0.9.0 <2.0.0'
  http: '>=0.9.0 <2.0.0'
  path: '>=0.9.0 <2.0.0'
