name: coverage
version: 0.6.4-dev
author: Dart Team <misc@dartlang.org>
description: Coverage data manipulation and formatting
homepage: https://github.com/dart-lang/coverage
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  args: '>=0.12.1 <1.0.0'
  http: '>=0.9.0 <2.0.0'
  logging: '>=0.9.0 <0.12.0'
  path: '>=0.9.0 <2.0.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
executables:
  collect_coverage:
  format_coverage:
